### ISSUE TITLE
Using ImGUI with an Evergine project targetting the Web

### ISSUE THREAD

**Issue by NinovanderMark** [EvergineTeam/ImGui.Net#4]
While working with Evergine I ran into the following issue for a project that targets the Web. After adding ImGUI per the [documentation](https://docs.evergine.com/2023.3.1/manual/extensions/imgui/setup.html) I'm no longer able to run the project that targets the Web platform, because the `cimgui.dll` file can't be found by Blazor.

```
Unhandled Exception: System.Exception: Workaround exception to leverage the actual one, not the wrong Delegate-related one
---> System.DllNotFoundException: cimgui
	at Evergine.UI.ImGuiManager.InitializeImGui()
	at Evergine.UI.ImGuiManager.Start()
	at Evergine.Framework.AttachableObject.BaseStart()
	at Evergine.Framework.Managers.SceneManagers.StartManagers()
	at Evergine.Framework.Scene.BaseStart()
	at Evergine.Framework.Services.ScreenContextManager.InitializeASingleScene(Scene scene)
	at Evergine.Framework.Services.ScreenContextManager.InitializeScreenContext(ScreenContext context)
	at Evergine.Framework.Services.ScreenContextManager.ToExecute(ScreenContext nextContext, ScreenTransition transition, Boolean doDispose)
```

I've tried copying the DLL from the `runtimes\win-x64\native` folder in the `.Windows` project to the `_framework` folder, and manually adding an entry for it to the `blazor.boot.json` but that did not resolve the issue.

Any help on getting this resolved would be much appreciated!

**Comment by jcant0n** [comment]
We have been working on adding support for more platforms, but the we is not currently supported. To enable it, we need to compile cimgui to WebAssembly and include it in the runtimes.
